mode				testing
version				one
models-directory		models/
config-directory 		config/
output-directory 		output/
gmsh-bin-directory 		~/gmsh-2.12.0-Linux/bin/
model-name			quadtest
config-name			simple
output-name			quadtest
delta-t				1 seconds
tracking-interval		1 hours
simulation-length		5 hours
contamination-mode-time 	constant
contamination-mode-space	constant
contamination 			1 au
tracking-mode			all
track				5
activate-plugin			defaults
