mode				testing
version				one
models-directory		models/
config-directory 		config/
output-directory 		output/
gmsh-bin-directory 		~/gmsh-2.12.0-Linux/bin/
model-name			fine1D
config-name			simple
output-name			asdasd-test
delta-t				1 seconds
tracking-interval		5 hours
simulation-length		50 days
contamination-mode-time 	constant
contamination-mode-space	constant
contamination 			1 au
tracking-mode			all
track				5
