mode				testing
version				one
models-directory		models/
config-directory 		config/
output-directory 		output/
gmsh-bin-directory 		~/gmsh-2.12.0-Linux/bin/
model-name			spread3d
config-name			simple
output-name			3d-spread-test
delta-t				20 seconds
tracking-interval		1 days
simulation-length		6 months
contamination-mode-time 	constant
contamination-mode-space	constant
contamination 			1 au
tracking-mode			all
track				5
