mode				testing
version				one
models-directory		models/
config-directory 		config/
output-directory 		output/
gmsh-bin-directory 		~/gmsh-2.12.0-Linux/bin/
model-name			round
config-name			simple
output-name			runtest
delta-t				60 seconds
tracking-interval		1 months
simulation-length		4 years
contamination-mode-time 	constant
contamination-mode-space	constant
contamination 			1e13 molesH3/m^3
tracking-mode			first-last
track				5
