// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Bitmap.H>
#include <FL/Fl_GIF_Image.H>
#include <FL/Enumerations.H>
#include <FL/fl_ask.H>
#include "Cartesian.h"
extern void userAction(Fl_Widget* target); 
extern void userAction(selection sel, Ca_Canvas* sender); 
extern void mark_data_dirty(); 
extern void reduce_all(); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *main_window;
  Fl_Group *grp_run_file;
  Fl_Text_Display *txdsp_run_file_name;
  Fl_Button *btn_open_run_file;
private:
  inline void cb_btn_open_run_file_i(Fl_Button*, void*);
  static void cb_btn_open_run_file(Fl_Button*, void*);
public:
  Fl_Button *btn_save_run_file;
private:
  inline void cb_btn_save_run_file_i(Fl_Button*, void*);
  static void cb_btn_save_run_file(Fl_Button*, void*);
public:
  Fl_Button *btn_preview_run_file;
private:
  inline void cb_btn_preview_run_file_i(Fl_Button*, void*);
  static void cb_btn_preview_run_file(Fl_Button*, void*);
public:
  Fl_Button *btn_revert_run_file;
private:
  inline void cb_btn_revert_run_file_i(Fl_Button*, void*);
  static void cb_btn_revert_run_file(Fl_Button*, void*);
public:
  Fl_Group *grp_current_files;
  Fl_Text_Display *txdsp_model_dir;
  Fl_Text_Display *txdsp_model_name;
  Fl_Text_Display *txdsp_settings_dir;
  Fl_Text_Display *txdsp_settings_name;
  Fl_Text_Display *txdsp_output_dir;
  Fl_Text_Display *txdsp_output_name;
  Fl_Button *btn_new_files;
private:
  inline void cb_btn_new_files_i(Fl_Button*, void*);
  static void cb_btn_new_files(Fl_Button*, void*);
public:
  Fl_Text_Editor *txedt_run_file_contents;
  Fl_Group *grp_simulation;
  Fl_Browser *brwsr_run_output;
  Fl_Double_Window *wndw_run_file;
  Fl_Browser *brwsr_run_file_preview;
  Fl_Double_Window *wndw_new_files;
  Fl_Group *grp_new_model;
  Fl_Text_Display *txdsp_new_model_dir;
  Fl_Button *btn_change_model_dir;
private:
  inline void cb_btn_change_model_dir_i(Fl_Button*, void*);
  static void cb_btn_change_model_dir(Fl_Button*, void*);
public:
  Fl_Browser *brwsr_model_name;
  Fl_Group *grp_new_settings;
  Fl_Text_Display *txdsp_new_settings_dir;
  Fl_Button *btn_change_settings_dir;
private:
  inline void cb_btn_change_settings_dir_i(Fl_Button*, void*);
  static void cb_btn_change_settings_dir(Fl_Button*, void*);
public:
  Fl_Browser *brwsr_settings_name;
  Fl_Group *grp_new_output;
  Fl_Text_Display *txdsp_new_output_dir;
  Fl_Button *btn_change_output_dir;
private:
  inline void cb_btn_change_output_dir_i(Fl_Button*, void*);
  static void cb_btn_change_output_dir(Fl_Button*, void*);
public:
  Fl_Text_Editor *txedt_new_output_name;
private:
  inline void cb_txedt_new_output_name_i(Fl_Text_Editor*, void*);
  static void cb_txedt_new_output_name(Fl_Text_Editor*, void*);
public:
  Fl_Button *btn_save_new_files;
private:
  inline void cb_btn_save_new_files_i(Fl_Button*, void*);
  static void cb_btn_save_new_files(Fl_Button*, void*);
public:
  Fl_Button *btn_revert_new_files;
private:
  inline void cb_btn_revert_new_files_i(Fl_Button*, void*);
  static void cb_btn_revert_new_files(Fl_Button*, void*);
public:
  void show();
  void start_showing_window();
};
#endif
