// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"
void userAction(Fl_Widget* target); 
void userAction(selection sel, Ca_Canvas* sender); 
void reduce_all(); 

Fl_Double_Window* UserInterface::make_window() {
  { main_window = new Fl_Double_Window(900, 510, "Tritium Diffusion Software - v0.1 - Chris Stuart");
    main_window->user_data((void*)(this));
    { grp_run_file = new Fl_Group(25, 102, 366, 326);
      grp_run_file->box(FL_THIN_UP_BOX);
      { txdsp_run_file_name = new Fl_Text_Display(30, 126, 351, 45, "Current run file:");
        txdsp_run_file_name->box(FL_THIN_UP_FRAME);
        txdsp_run_file_name->align(Fl_Align(FL_ALIGN_CENTER));
      } // Fl_Text_Display* txdsp_run_file_name
      grp_run_file->end();
    } // Fl_Group* grp_run_file
    main_window->size_range(900, 510, 900, 510);
    main_window->end();
  } // Fl_Double_Window* main_window
  return main_window;
}

void UserInterface::show() {
  make_window();
  //ChnButton[0]=Chn0;
  main_window->show();
}
