// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Bitmap.H>
#include <FL/Fl_GIF_Image.H>
#include "Cartesian.h"
extern void userAction(Fl_Widget* target); 
extern void userAction(selection sel, Ca_Canvas* sender); 
extern void reduce_all(); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *main_window;
  Fl_Group *grp_run_file;
  Fl_Text_Display *txdsp_run_file_name;
  void show();
};
#endif
